// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniWebAPI.Models;

namespace UniWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210807122156_mymigratonone")]
    partial class mymigratonone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("UniWebAPI.Models.Collage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colleges");
                });

            modelBuilder.Entity("UniWebAPI.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("UniWebAPI.Models.NewsImg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("NewId")
                        .HasColumnType("int");

                    b.Property<string>("img")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NewId");

                    b.ToTable("NewsImgs");
                });

            modelBuilder.Entity("UniWebAPI.Models.PostGraduteMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CollageCertificateFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollageGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GradutePrencetage")
                        .HasColumnType("real");

                    b.Property<int>("GraduteYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("InterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InterviewPassed")
                        .HasColumnType("int");

                    b.Property<string>("MasterType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostGraduteId")
                        .HasColumnType("int");

                    b.Property<int>("RequestAccepted")
                        .HasColumnType("int");

                    b.Property<string>("StatementGradesFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("accepted")
                        .HasColumnType("int");

                    b.Property<float>("expancesAmount")
                        .HasColumnType("real");

                    b.Property<DateTime>("expancesDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("expancesDone")
                        .HasColumnType("int");

                    b.Property<string>("expancesReciepts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("matchingPaper")
                        .HasColumnType("int");

                    b.Property<DateTime>("matchingPaperDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("registerDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PostGraduteId");

                    b.ToTable("PostGraduteMasters");
                });

            modelBuilder.Entity("UniWebAPI.Models.PostGradutePhd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("InterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InterviewPassed")
                        .HasColumnType("int");

                    b.Property<string>("MasterCertificateFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MasterYear")
                        .HasColumnType("int");

                    b.Property<string>("PhdType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostGraduteId")
                        .HasColumnType("int");

                    b.Property<int>("RequestAccepted")
                        .HasColumnType("int");

                    b.Property<int>("accepted")
                        .HasColumnType("int");

                    b.Property<float>("expancesAmount")
                        .HasColumnType("real");

                    b.Property<DateTime>("expancesDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("expancesDone")
                        .HasColumnType("int");

                    b.Property<string>("expancesReciepts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("matchingPaper")
                        .HasColumnType("int");

                    b.Property<DateTime>("matchingPaperDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("registerDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PostGraduteId");

                    b.ToTable("PostGradutePhds");
                });

            modelBuilder.Entity("UniWebAPI.Models.PostGradutesDiploma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CollageCertificateFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollageGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiplomaType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GradutePrencetage")
                        .HasColumnType("real");

                    b.Property<int>("GraduteYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("InterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InterviewPassed")
                        .HasColumnType("int");

                    b.Property<int>("PostGraduteId")
                        .HasColumnType("int");

                    b.Property<int>("RequestAccepted")
                        .HasColumnType("int");

                    b.Property<string>("StatementGradesFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("accepted")
                        .HasColumnType("int");

                    b.Property<float>("expancesAmount")
                        .HasColumnType("real");

                    b.Property<DateTime>("expancesDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("expancesDone")
                        .HasColumnType("int");

                    b.Property<string>("expancesReciepts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("matchingPaper")
                        .HasColumnType("int");

                    b.Property<DateTime>("matchingPaperDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("registerDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PostGraduteId");

                    b.ToTable("PostGradutesDiplomas");
                });

            modelBuilder.Entity("UniWebAPI.Models.PostGradutesInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AcknowledmentFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcknowledmentJobFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApproveAffairFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthCertificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Collage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuerSSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilirityStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilirtyFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nameen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Password")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSDFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SalltPassword")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("birthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PostGradutesInfos");
                });

            modelBuilder.Entity("UniWebAPI.Models.UniversityInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniMassage_ar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniMassage_en")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniName_ar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniName_en")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniPresidentSpeech_ar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniPresidentSpeech_en")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniVisionar_ar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniVisionar_en")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("universityInfos");
                });

            modelBuilder.Entity("UniWebAPI.Models.NewsImg", b =>
                {
                    b.HasOne("UniWebAPI.Models.News", "news")
                        .WithMany()
                        .HasForeignKey("NewId");

                    b.Navigation("news");
                });

            modelBuilder.Entity("UniWebAPI.Models.PostGraduteMaster", b =>
                {
                    b.HasOne("UniWebAPI.Models.PostGradutesInfo", "PostGradutes")
                        .WithMany()
                        .HasForeignKey("PostGraduteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostGradutes");
                });

            modelBuilder.Entity("UniWebAPI.Models.PostGradutePhd", b =>
                {
                    b.HasOne("UniWebAPI.Models.PostGradutesInfo", "PostGradutes")
                        .WithMany()
                        .HasForeignKey("PostGraduteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostGradutes");
                });

            modelBuilder.Entity("UniWebAPI.Models.PostGradutesDiploma", b =>
                {
                    b.HasOne("UniWebAPI.Models.PostGradutesInfo", "PostGradutes")
                        .WithMany()
                        .HasForeignKey("PostGraduteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostGradutes");
                });
#pragma warning restore 612, 618
        }
    }
}
